# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionTb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=255)),
                ('color_rgb', models.CharField(max_length=255)),
                ('color_score', models.CharField(max_length=255)),
                ('color_fraction', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_score', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'vision_tb',
                'managed': True,
            },
        ),
    ]
