# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_list', models.CharField(max_length=255)),
                ('score_list', models.CharField(max_length=255)),
                ('fraction_list', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DominantColors',
        ),
    ]
