# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_controller', '0003_auto_20171115_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionresults',
            name='image_url',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='visionresults',
            table='vision_tb',
        ),
    ]
