# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_controller', '0005_auto_20171122_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiontb',
            name='happen_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2017, 12, 1)),
        ),
    ]
